### ISSUE TITLE
amqp only connect with default credentials (guest:guest)

### ISSUE THREAD

**Issue by edgaru** [actumn/celery.node#8]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When I try to connect with credentials the applications tries to connect with guest:guest

I am using:

const client = celery.createClient({
	CELERY_BROKER:  'amqp://test:password@localhost:5672/test'
});

* **What is the expected behavior?**

Connect to rabbitmq using credentials different than guest.

* **Please tell us about your environment:**
  
  - Version: 0.0.0
  - OS: linux
  - Language: ES6/7

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by actumn** [comment]
Hi, edgaru!
Thank you for reporting!!
I will fix it as soon as possible!

**Comment by actumn** [comment]
I have fixed it and published 0.0.1.
Can you check the bug occurs again?

**Comment by edgaru** [comment]
Its works, thank you.

**Comment by monstermac77** [comment]
It looks like there's still a small problem here, which probably has gone unnoticed. Even when specifying credentials, it seems as though celery.node will attempt to connect as the user specified but will also still attempt to connect as guest. For instance, when initing a client like so: 

`const celeryClient = celery.createClient('amqp://devRabbitMQUser:[redacted]@localhost/dev');` 

and then calling a task like so: 

```
const pushTask = celeryClient.createTask('sender.send');
pushTask.applyAsync([[req.body]]);
```

I see the following logs: 

```
==> rabbit@coursiclePush.log <==
2024-09-29 05:21:42.366 [info] <0.6001.5> accepting AMQP connection <0.6001.5> (127.0.0.1:42694 -> 127.0.0.1:5672)
2024-09-29 05:21:42.368 [info] <0.6004.5> accepting AMQP connection <0.6004.5> (127.0.0.1:42706 -> 127.0.0.1:5672)
2024-09-29 05:21:42.419 [info] <0.6004.5> connection <0.6004.5> (127.0.0.1:42706 -> 127.0.0.1:5672): user 'devRabbitMQUser' authenticated and granted access to vhost 'dev'
2024-09-29 05:21:42.419 [info] <0.6001.5> connection <0.6001.5> (127.0.0.1:42694 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
```

This had me stuck for a while because I had deleted the guest user and so any time I tried to add a task the node server would crash and say `PLAIN login refused: user 'guest' - invalid credentials`, which didn't make sense because I wasn't connecting as the guest user. 

In any case, keeping the guest user around prevents the crash so it's good enough for now. Hopefully this will be helpful to anyone else who tried to preemptively lock down their RabbitMQ users like I did. This is a fantastic library and I really appreciate your work on it @actumn (you've been so responsive to users too!)
